"""add ingested_repos table

Revision ID: b56026b3c18f
Revises: e82fffff4495
Create Date: 2026-07-19 22:44:36.921937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b56026b3c18f'
down_revision: Union[str, Sequence[str], None] = 'e82fffff4495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingested_repos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('github_url', sa.String(), nullable=False),
    sa.Column('repo_id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingested_repos_id'), 'ingested_repos', ['id'], unique=False)
    op.create_index(op.f('ix_ingested_repos_job_id'), 'ingested_repos', ['job_id'], unique=True)
    op.create_index(op.f('ix_ingested_repos_user_id'), 'ingested_repos', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingested_repos_user_id'), table_name='ingested_repos')
    op.drop_index(op.f('ix_ingested_repos_job_id'), table_name='ingested_repos')
    op.drop_index(op.f('ix_ingested_repos_id'), table_name='ingested_repos')
    op.drop_table('ingested_repos')
    # ### end Alembic commands ###
