"""add updated_at, unique constraint on user_id+repo_id

Revision ID: b991397be2fd
Revises: b56026b3c18f
Create Date: 2026-07-22 15:21:38.656638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b991397be2fd'
down_revision: Union[str, Sequence[str], None] = 'b56026b3c18f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingested_repos', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_index(op.f('ix_ingested_repos_job_id'), table_name='ingested_repos')
    op.create_index(op.f('ix_ingested_repos_repo_id'), 'ingested_repos', ['repo_id'], unique=False)
    op.create_unique_constraint('uq_user_repo', 'ingested_repos', ['user_id', 'repo_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_repo', 'ingested_repos', type_='unique')
    op.drop_index(op.f('ix_ingested_repos_repo_id'), table_name='ingested_repos')
    op.create_index(op.f('ix_ingested_repos_job_id'), 'ingested_repos', ['job_id'], unique=True)
    op.drop_column('ingested_repos', 'updated_at')
    # ### end Alembic commands ###
